AllCops:
  TargetRubyVersion: 3.1.4
  NewCops: enable
  Exclude:
    - 'bin/**/*'

Gemspec/DevelopmentDependencies:
  EnforcedStyle: gemspec

Metrics/AbcSize:
  Max: 20

Metrics/CollectionLiteralLength:
  Enabled: false

Metrics/ModuleLength:
  Exclude:
    - 'lib/rack/cloudflare/countries.rb'

RSpec/ExampleLength:
  Max: 15

Style/Documentation:
  Enabled: false